version: "3"

services:
  bot:
    build: .
    restart: always
    privileged: true
    links:
      - redis
    environment:
      - PETROL_TOKEN

  redis:
    restart: always
    image: redis:6.0.4-alpine
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
