version: "3"

services:
  bot:
    build: .
    restart: always
    privileged: true
    links:
      - redis
    networks:
      - internal_network
      - external_network
    environment:
      - PETROL_TOKEN

  redis:
    restart: always
    image: redis:6.0.4-alpine
    networks:
      - internal_network
    
networks:
  internal_network:
    internal: true
  external_network:
