on:
  push:
    branches:
      - develop

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  TARGET_IP: ${{ secrets.TARGET_IP }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Deploy with rsync'
      run: |
        echo "$SECRET_KEY" > secret.pem
        chmod 600 secret.pem
        sudo apt install rsync
        ssh-keyscan -H $TARGET_IP > known_hosts 2>&1
        rsync -av -e "ssh -o UserKnownHostsFile=known_hosts -i secret.pem" ./ minnet@$TARGET_IP:/home/minnet/gsbot
        ssh -o UserKnownHostsFile=known_hosts -i secret.pem minnet@$TARGET_IP "cd gsbot; docker-compose down; docker-compose build && docker-compose up -d"
